### ISSUE TITLE
Yolov3.weights is inaccessible/unavailable/missing.

### ISSUE THREAD

**Issue by anoduck** [embium/playwright-nonocaptcha#5]
The site [https://mikey.id/yolov3.weights](https://mikey.id/yolov3.weights) either does not exist, is down, or is inactive. So, the file yolov3.weights is inaccessible and/or unavailable, and without it the module will not run.

**Comment by Lomme1020** [comment]
Hi, I have the same problem

Do you found the solution or a "temporaly solution" ?

Thanks

**Comment by anoduck** [comment]
@Lomme1020 I found a working solution other than the one provided in this project repository. I installed captcha buster as an extension for geckodriver using selenium in python, and have not encountered a captcha so far in my test runs.

**Comment by Lomme1020** [comment]
@anoduck Ok thanks

**Comment by Lomme1020** [comment]
@anoduck Sorry but where did you download captcha buster ? you have a link ?

**Comment by anoduck** [comment]
> @anoduck Sorry but where did you download captcha buster ? you have a link ?

@Lomme1020 No worries, I had to do some digging to find it myself, because there are several projects with the same name or similar. 

The repo is: https://github.com/dessant/buster

**For chrome:** [This Link fer Chrome](https://github.com/dessant/buster/releases/download/v1.3.1/buster_captcha_solver_for_humans-1.3.1-chrome.zip)

**For Firefox:** [This Link fer Firefox](https://github.com/dessant/buster/releases/download/v1.3.1/buster_captcha_solver_for_humans-1.3.1-firefox.zip)

1. Choose your poison
2. Download the archive from the link
3. Unzip the archive
4. The file extension for the firefox extension is '.xpi'. 
5. How it is installed is dependent on what you are doing.
6. If you feel inclined to do so, you may perform a happy dance.
